bln/routes/web.php
<?php
if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
 }

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('locale/{locale}', function ($locale){
    Session::put('locale', $locale);
    return redirect()->back();
});




Route::prefix('admin/')->group(function () {
Route::group(['middleware' => ['get.menu']], function () {
    Route::get('/home', function () {           return view('dashboard.homepage'); })->middleware('auth');

    Route::group(['middleware' => ['role:user']], function () {
        
        Route::get('/404', function () {        return view('dashboard.404'); });
        Route::get('/500', function () {        return view('dashboard.500'); });

		Route::resource('red_genie', 'RedGenieController');
		Route::get('/red_genie/reg_links/{redgenieId}', 'RedGenieController@regLinks')->name('red_genie.reg_links');
		Route::get('/red_genie/add_reg_links/{redgenieId}', 'RedGenieController@addRegLinks');
		Route::post('/red_genie/save_reg_links/{redgenieId}', 'RedGenieController@saveRegLinks');
		
		
		Route::resource('sales_genie', 'SalesGenieController');
		Route::get('/sales_genie/reg_links/{redgenieId}', 'SalesGenieController@regLinks')->name('sales_genie.reg_links');
		Route::get('/sales_genie/add_reg_links/{redgenieId}', 'SalesGenieController@addRegLinks');
        Route::post('/sales_genie/save_reg_links/{redgenieId}', 'SalesGenieController@saveRegLinks');
        Route::post('/sales_genie/delete_reg_links/{id}/{sg_id}', 'SalesGenieController@deleteRegLinks')->name('reg_links.destroy');
        
        Route::resource('customers', 'CustomerController');
        
        Route::resource('settings', 'SettingsController');
        
        Route::resource('resource_center', 'ResourceCenterController');

        Route::get('credits', 'CreditController@index')->name('credits.index');
        Route::get('credits/{refferal_code}', 'CreditController@view');
        Route::get('points/create', 'PointController@create')->name('points.create');
        Route::post('points/store', 'PointController@store')->name('points.store');
        Route::get('points', 'PointController@index')->name('points.index');
        Route::get('points/{invoice_no}', 'PointController@view');
        Route::get('points/{id}/edit', 'PointController@edit');
        Route::post('points/{id}/update', 'PointController@update');
		
		Route::get('network', 'NetworkController@index');
        Route::get('network_tree_view', 'NetworkController@network_tree_view')->name('network_tree_view');
		
		
    });
    Auth::routes();

    Route::resource('resource/{table}/resource', 'ResourceController')->names([
        'index'     => 'resource.index',
        'create'    => 'resource.create',
        'store'     => 'resource.store',
        'show'      => 'resource.show',
        'edit'      => 'resource.edit',
        'update'    => 'resource.update',
        'destroy'   => 'resource.destroy'
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
        
        Route::resource('users',        'UsersController');
        Route::resource('roles',        'RolesController');
        Route::get('/roles/move/move-up',      'RolesController@moveUp')->name('roles.up');
        Route::get('/roles/move/move-down',    'RolesController@moveDown')->name('roles.down');
        Route::prefix('menu/element')->group(function () { 
            Route::get('/',             'MenuElementController@index')->name('menu.index');
            Route::get('/move-up',      'MenuElementController@moveUp')->name('menu.up');
            Route::get('/move-down',    'MenuElementController@moveDown')->name('menu.down');
            Route::get('/create',       'MenuElementController@create')->name('menu.create');
            Route::post('/store',       'MenuElementController@store')->name('menu.store');
            Route::get('/get-parents',  'MenuElementController@getParents');
            Route::get('/edit',         'MenuElementController@edit')->name('menu.edit');
            Route::post('/update',      'MenuElementController@update')->name('menu.update');
            Route::get('/show',         'MenuElementController@show')->name('menu.show');
            Route::get('/delete',       'MenuElementController@delete')->name('menu.delete');
        });
        Route::prefix('menu/menu')->group(function () { 
            Route::get('/',         'MenuController@index')->name('menu.menu.index');
            Route::get('/create',   'MenuController@create')->name('menu.menu.create');
            Route::post('/store',   'MenuController@store')->name('menu.menu.store');
            Route::get('/edit',     'MenuController@edit')->name('menu.menu.edit');
            Route::post('/update',  'MenuController@update')->name('menu.menu.update');
            Route::get('/delete',   'MenuController@delete')->name('menu.menu.delete');
        });
        
    });
});


});


//frontend

Route::get('/signup', function(){return view('frontend.login.signup');})->name('frontend.signup');
Route::post('/signup', 'frontend\CustomersController@register');


Route::get('/', 'Auth\FrontendLoginController@showLoginForm');
Route::get('/login', 'Auth\FrontendLoginController@showLoginForm')->name('frontend.login');
Route::post('/login', 'Auth\FrontendLoginController@login')->name('frontend.login.post');
Route::post('/logout', 'Auth\FrontendLoginController@logout')->name('frontend.logout');

Route::get('/registration/{refId}', 'frontend\CustomersController@completeRegistration')->name('complete_registration');
Route::post('/registration/{refId}', 'frontend\CustomersController@updateRegistration');


//password reset routes
Route::post('reset_password_without_token', 'frontend\AccountsController@validatePasswordRequest');
Route::post('reset_password_with_token', 'frontend\AccountsController@resetPassword');
Route::get('/forgot-password', 'frontend\AccountsController@forgot_password');
Route::get('password/reset/{token}', 'frontend\AccountsController@showPasswordResetForm');
Route::post('reset-password/{token}', 'frontend\AccountsController@resetPassword_submit')->name('my_route');




Route::group(['middleware'=>'frontend'], function() {
    Route::get('/profile', 'frontend\ProfileController@index')->name('profile');
	Route::post('/profile_update', 'frontend\ProfileController@update');
    Route::post('/exp_update', 'frontend\ProfileController@expUpdate');
    Route::get('/exp_remove/{id}', 'frontend\ProfileController@expRemove');
    
    Route::get('/resource_center', 'frontend\ProfileController@resourceCenter')->name('resource_center');
    Route::get('/statements', 'frontend\StatementController@index')->name('statements');
    Route::post('/statements', 'frontend\StatementController@index');

    Route::get('/statements/credits', 'frontend\StatementController@credits')->name('statements.credits');
    Route::post('/statements/credits', 'frontend\StatementController@credits');

    Route::get('/create_salesgenie', 'frontend\FrontendSalesGenieController@create')->name('create_salesgenie');
    Route::post('/create_salesgenie', 'frontend\FrontendSalesGenieController@store')->name('add_salesgenie');

    Route::get('/invites', 'frontend\FrontendSalesGenieController@invites')->name('invites');
    Route::post('/invites', 'frontend\FrontendSalesGenieController@addInvites')->name('add_invites');
	
	//network routes
    Route::get('/network', 'frontend\ProfileController@network')->name('network');
    Route::post('/ajax_network', 'frontend\ProfileController@customers_row');

    
    Route::post('/crop-image', 'frontend\ImageController@uploadImage')->name('upload.image');
});

Route::get('/get_profile_pic/{id}/{opt?}', 'frontend\ProfileController@getProfilePic');

//Apis

Route::post('/profile-verification', 'frontend\RedCreditsController@add')->name('add_red_credit');
Route::post('/payment_completion', 'frontend\RedPointsController@add')->name('add_red_point');

bln/app/Models/ResourceCenters.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ResourceCenters extends Model
{
    protected $table = 'resource_center';
	//public $timestamps = false;
	
	
}

bln/app/Http/Controllers/ResourceCenterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Models\ResourceCenters;


class ResourceCenterController extends Controller
{
    
    
	 /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		
        $rcs = DB::table('resource_center')->orderBy('created_at', 'desc')->paginate(10);
		
        //echo '<pre>';print_r($redgenies);exit;
        $breadcrumbs[0]['title']='Resource Centre';
		
        return view('dashboard.resource_centers.list', ['rcs' => $rcs,'breadcrumbs' => $breadcrumbs]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        $breadcrumbs[0]['title']='Resource Centre';
        $breadcrumbs[0]['link']=url('admin/resource_center');
        $breadcrumbs[1]['title']='Add';
        return view('dashboard.resource_centers.create',compact('breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            
            'title'           => 'required',
			'link'           => 'required'
        ]);
      
	   
	   
	   	 
			 
	    $rc=new ResourceCenters();
		$rc->title = $request->input('title');
		$rc->link = $request->input('link');
		$rc->type = $request->input('type');
        $rc->is_featured = $request->input('featured');
        $rc->resource_for = $request->input('r_for');
        $rc->status = $request->input('status');
		$rc->save();

	   
	   
        $request->session()->flash('message', ' Resources created Successfully');
        return redirect()->route('resource_center.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
		
		$rc = ResourceCenters::find($id);
        
        $breadcrumbs[0]['title']='Resource Centre';
        $breadcrumbs[0]['link']=url('admin/resource_center');
        $breadcrumbs[1]['title']='View';
		
        return view('dashboard.resource_centers.show', [ 'rc' => $rc,'breadcrumbs' => $breadcrumbs ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rc = ResourceCenters::find($id);
        //$rc = DB::table('resource_center')->where('id',$id)->get();
        
        $breadcrumbs[0]['title']='Resource Centre';
        $breadcrumbs[0]['link']=url('admin/resource_center');
        $breadcrumbs[1]['title']='Edit';
        
        return view('dashboard.resource_centers.edit', ['rc' => $rc,'breadcrumbs' => $breadcrumbs ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $validatedData = $request->validate([
            
            'title'           => 'required',
			'link'           => 'required'
        ]);
		
		
        $rc = ResourceCenters::find($id);
        
       
        $rc->title = $request->input('title');
		$rc->link = $request->input('link');
		$rc->type = $request->input('type');
        $rc->is_featured = $request->input('featured');
        $rc->resource_for = $request->input('r_for');
        $rc->status = $request->input('status');
		$rc->save();
		
		
		
		
        $request->session()->flash('message', 'Resources edited Successfully');
        return redirect()->route('resource_center.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $rc = ResourceCenters::find($id);
		
        if($rc){
            
            $rc->delete();
        }
        
        
        return redirect()->route('resource_center.index');
    }
	
	
	
}

bln/resources/views/dashboard/resource_centers/create.blade.php
@extends('dashboard.base')

@section('content')


        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8">
			  
			  
			  
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Create Resource') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('resource_center.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label> Title</label>
                                <input class="form-control" type="text" placeholder="Title" name="title" required autofocus>
                            </div>
							
							
							<div class="form-group row">
                                <label>Link</label>
                                <input class="form-control" type="text" placeholder="link" name="link" required autofocus>
                            </div>
							
							<div class="form-group row">
                                <label>Type</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="type" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='1'>Training Manual</option>
							<option value='2'>Articles</option>
                            <option value='3'>Case Studies</option>
							<option value='4'>Videos</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>For</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="r_for" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='1'>Red Genies</option>
							<option value='2'>Sales Genies </option>
                            <option value='3'>Customers</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>Featured</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="featured" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='0'>False</option>
							<option value='1'>True</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>Status</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="status" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='0'>Disabled</option>
							<option value='1'>Enabled</option>
							</select>
							</div>

                           
 
                            <button class="btn btn-block btn-success" type="submit">{{ __('Add') }}</button>
                            <a href="{{ route('resource_center.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')

@endsection

bln/resources/views/dashboard/resource_centers/edit.blade.php
@extends('dashboard.base')

@section('content')


        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8">
			  
			  
			  
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> {{ __('Edit Resource') }}</div>
                    <div class="card-body">
                        <form method="POST" action="{{url('admin/resource_center/'.$rc->id)}}">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label> Title</label>
                                <input class="form-control" type="text" placeholder="Title" name="title" value="{{@ $rc->title}}" required autofocus>
                            </div>
							
							
							<div class="form-group row">
                                <label>Link</label>
                                <input class="form-control" type="text" placeholder="link" name="link" value="{{@ $rc->link}}" required autofocus>
                            </div>
							
							<div class="form-group row">
                                <label>Type</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="type" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='1' @if($rc->type==1) selected @endif >Training Manual</option>
							<option value='2' @if($rc->type==2) selected @endif >Articles</option>
                            <option value='3' @if($rc->type==3) selected @endif >Case Studies</option>
							<option value='4' @if($rc->type==4) selected @endif >Videos</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>For</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="r_for" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='1' @if($rc->resource_for==1) selected @endif >Red Genies</option>
							<option value='2' @if($rc->resource_for==2) selected @endif >Sales Genies </option>
                            <option value='3' @if($rc->resource_for==3) selected @endif >Customers</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>Featured</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="featured" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='0' @if($rc->is_featured==0) selected @endif >False</option>
							<option value='1' @if($rc->is_featured==1) selected @endif >True</option>
							</select>
							</div>

                            <div class="form-group row">
                                <label>Status</label>
               <!-- <input class="form-control" type="email" placeholder="{{ __('Email Id') }}" name="email_id" required autofocus>-->
                            <select class="form-control" name="status" required autofocus>
							<option value=''>--Select Type--</option>
							<option value='0' @if($rc->status==0) selected @endif >Disabled</option>
							<option value='1' @if($rc->status==1) selected @endif >Enabled</option>
							</select>
							</div>

                           
 
                            <button class="btn btn-block btn-success" type="submit">{{ __('Save') }}</button>
                            <a href="{{ route('resource_center.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a> 
                        </form>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection

@section('javascript')

@endsection

bln/resources/views/dashboard/resource_centers/list.blade.php
@extends('dashboard.base')

@section('content')




        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i>{{ __('Resource Centre') }}</div>
                    <div class="card-body">
                        <div class="row"> 
                          <a href="{{ route('resource_center.create') }}" class="btn btn-primary m-2">{{ __('Add New') }}</a>
                        </div>
                        <br>
                        <table class="table table-responsive-sm table-striped">
                        <thead>
                          <tr>
                            <th>Title</th>
                            <th>Link</th>
                            <th>Type</th>
                            <th>For</th>
                            <th>Status</th>
                            
                            
							<th></th>
							<th></th>
							<th></th>
							<th></th>
                            
                          </tr>
                        </thead>
                        <tbody>
                          @foreach($rcs as $rc)


                          <?php

switch ($rc->type) {
  case "1":
      $rc_type = "Training Manual";
  break;
  case "2":
      $rc_type = "Articles";
  break;
  case "3":
      $rc_type = "Case Studies";
  break;
  case "4":
      $rc_type = "Videos";
  break;
  default:
  $rc_type = "";
  break;
};

switch ($rc->resource_for) {
  case "1":
      $rc_resource_for = "Red Genies";
  break;
  case "2":
      $rc_resource_for = "Sales Genies";
  break;
  case "3":
      $rc_resource_for = "Customers";
  
  
};

switch ($rc->is_featured) {
  case "0":
      $rc_is_featured = "No";
  break;
  case "1":
      $rc_is_featured = "Yes";
  
  
};

switch ($rc->status) {
  case "0":
      $rc_status = "Disabled";
  break;
  case "1":
      $rc_status = "Enabled";
  
  
};
?>

                            <tr>
                              <td><strong>{{ $rc->title }}</strong></td>
                              <td><strong>{{ $rc->link }}</strong></td>
                              <td><strong>{{ $rc_type }}</strong></td>
                              <td><strong>{{ $rc_resource_for }}</strong></td>
                              <td><strong>{{ $rc_status }}</strong></td>
                             
                              
                              
							  
							  <td>
                                <!--<a href="{{ url('/red_genie/reg_links/' . $note->id) }}" class="btn btn-block btn-primary">Reg Links</a>-->
                              </td>
                              <td>
                                <a href="{{ url('admin/resource_center/' . $rc->id) }}" class="btn btn-block btn-primary">View</a>
                              </td>
                              <td>
                                <a href="{{ url('admin/resource_center/' . $rc->id . '/edit') }}" class="btn btn-block btn-primary">Edit</a>
                              </td>
                              <td>
                                <form action="{{ route('resource_center.destroy', $rc->id ) }}" method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-block btn-danger">Delete</button>
                                </form>
                              </td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                     {{ $rcs->links() }}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection


@section('javascript')

@endsection

bln/resources/views/dashboard/resource_centers/show.blade.php
@extends('dashboard.base')

@section('content')

        <div class="container-fluid">
          <div class="animated fadeIn">
            <div class="row">
              <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                      <i class="fa fa-align-justify"></i> Resource</div>
                    <div class="card-body">
					
<?php

switch ($rc->type) {
  case "1":
      $rc_type = "Training Manual";
  break;
  case "2":
      $rc_type = "Articles";
  break;
  case "3":
      $rc_type = "Case Studies";
  break;
  case "4":
      $rc_type = "Videos";
  break;
  default:
  $rc_type = "";
  break;
};

switch ($rc->resource_for) {
  case "1":
      $rc_resource_for = "Red Genies";
  break;
  case "2":
      $rc_resource_for = "Sales Genies";
  break;
  case "3":
      $rc_resource_for = "Customers";
  
  
};

switch ($rc->is_featured) {
  case "0":
      $rc_is_featured = "No";
  break;
  case "1":
      $rc_is_featured = "Yes";
  
  
};

switch ($rc->status) {
  case "0":
      $rc_status = "Disabled";
  break;
  case "1":
      $rc_status = "Enabled";
  
  
};

echo 'sd'.$rc_resource_for;
?>

					<table style="width:100%;margin-bottom:25px;">
		<tr><td><h4>Title</h4></td><td><h4>: {{ $rc->title }}</h4></td></tr>	
		<tr><td><h4>Link</h4></td><td><h4>: {{ $rc->link }}</h4></td></tr>
		<tr><td><h4>Type</h4></td><td><h4>: {{ $rc_type }}</h4></td></tr>
		<tr><td><h4>For</h4></td><td><h4>: {{ $rc_resource_for }}</h4></td></tr>
		<tr><td><h4>Featured</h4></td><td><h4>: {{ $rc_is_featured }}</h4></td></tr>
		<tr><td><h4>Status</h4></td><td><h4>: {{ $rc_status }}</h4></td></tr>
		
					
					</table>
                       
                        
                        <a href="{{ route('resource_center.index') }}" class="btn btn-block btn-primary">{{ __('Return') }}</a>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

@endsection


@section('javascript')

@endsection